model:
  model_based:
    project: similarity-movie-recommender-system
    random_state: 42
    train_size: 0.8
    test_size: 0.2
    
  memory_based:
    item_item_based:
      project: similarity-movie-recommender-system
      random_state: 42
      train_size: 0.8
      test_size: 0.2

    user_user_based:
      project: similarity-movie-recommender-system
      random_state: 42
      train_size: 0.8
      test_size: 0.2

data_source:
  ratings: "https://drive.google.com/uc?id=10kqzyYE9As0bxkBlo4Q2V3xasW_y4Ssl"



artifacts:
  dataset_name: ratings.csv
  artifacts_dir: movieflix/artifacts
  raw_local_data_dir: movieflix/artifacts/raw_local_data_dir
  clean_local_data_dir: movieflix/artifacts/clean_local_data_dir
  latest_model_dir: movieflix/artifacts/latest_model_dir
  model_metrics_dir: movieflix/artifacts/model_metrics_dir
  train_data_dir: movieflix/artifacts/train_data_dir
  test_data_dir: movieflix/artifacts/test_data_dir
  metrics_dir: movieflix/artifacts/metrics_dir
